# Site settings
name: Moonface Space
title: You'll never walk alone
email: mr.moonfacex@gmail.com
description: "enjoy coding && thinking"
baseurl: "http://moonfacex.github.io/moonface.github.io"

# Build settings
markdown: kramdown
permalinks: pretty
